stages:
- stage: Build

  jobs:
  - job: BuildJob

    steps:
    - checkout: none
    - task: NodeTool@0
      inputs:
        versionSpec: '16.x'

    - script: npm install
    - template: templates/build-template.yml
    - task: PublishBuildArtifacts@1
      inputs:
        pathToPublish: '$(Build.ArtifactStagingDirectory)'
