# Test case for step spacing after conditionals and templates
stages:
- stage: Build

  jobs:
  - job: BuildJob

    steps:
    - ${{ if ne(parameters.artifactsBuildId, '') }}:
      - checkout: none
      - template: /steps/download-artifacts.yaml
        parameters:
          artifactName: $(artifactName)

    - checkout: self
      clean: true

    - ${{ parameters.preSteps }}
    - template: /steps/restore-and-build.yaml
      parameters:
        solutionFile: solution.sln

    - bash: echo "Final step"
